window:
  padding:
    x: 5
    y: 5
  dimensions:
    columns: 100
    lines: 30
  opacity: 0.9

scrolling:
  history: 5000
  multiplier: 3

font:
  normal:
    family: Fira Code
    style: Medium
  size: 15

cursor:
  style:
    shape: Underline
    blinking: Always
    blink-interval: 750
